version: "3.8"

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-samirhassen/enkantaa-frontend}:${IMAGE_TAG:-latest}
    container_name: enkantaa-frontend-production
    restart: unless-stopped
    ports:
      - "9898:9898"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge

